export const faculties = [
  'Agriculture',
  'Arts',
  'Basic Medical Sciences',
  'Biological Sciences',
  'Business Administration',
  'Clinical Sciences',
  'Education',
  'Engineering',
  'Environmental Sciences',
  'Law',
  'Management Sciences',
  'Medical Sciences',
  'Pharmaceutical Sciences',
  'Science',
  'Social Sciences',
  'Veterinary Medicine',
  'Vocational Technical Education',
  'Communication and Media Studies',
  'Computing and Informatics',
  'Health Sciences',
  'Humanities',
  'Library and Information Science',
  'Transport',
];

export const departments = {
  Agriculture: [
    'Animal Science',
    'Agricultural Economics',
    'Agricultural Extension',
    'Crop Production',
    'Soil Science',
    'Fisheries and Wildlife Management',
    'Agricultural Education',
    'Agricultural Engineering',
    'Food Science and Technology',
    'Home Science and Management',
  ],
  Arts: [
    'English and Literary Studies',
    'History and International Studies',
    'Philosophy',
    'Linguistics and Nigerian Languages',
    'Music',
    'Theatre and Film Studies',
    'Fine and Applied Arts',
    'Religious Studies',
    'Arabic and Islamic Studies',
    'European Studies',
    'Communication and Language Arts',
    'African Languages and Cultures',
    'French',
    'Archaeology and Heritage Studies',
    'Sociology',
    'Psychology',
  ],
  'Basic Medical Sciences': [
    'Anatomy',
    'Physiology',
    'Biochemistry',
    'Medical Microbiology',
    'Medical Laboratory Science',
    'Chemical Pathology',
    'Haematology and Blood Transfusion',
    'Morbid Anatomy',
    'Histopathology',
  ],
  'Biological Sciences': [
    'Biochemistry',
    'Microbiology',
    'Zoology',
    'Botany',
    'Genetics and Biotechnology',
    'Plant Science and Biotechnology',
    'Environmental Biology',
  ],
  'Business Administration': [
    'Accounting',
    'Banking and Finance',
    'Business Management',
    'Marketing',
    'Public Administration',
    'Entrepreneurship',
    'Procurement Management',
    'Agribusiness',
  ],
  'Clinical Sciences': [
    'Medicine',
    'Surgery',
    'Paediatrics',
    'Obstetrics and Gynaecology',
    'Ophthalmology',
    'Psychiatry',
    'Radiology',
    'Anaesthesia',
    'Community Medicine',
    'Oto-Rhino-Laryngology',
  ],
  Education: [
    'Educational Psychology and Counselling',
    'Arts and Social Science Education',
    'Science Education',
    'Mathematics Education',
    'Physical and Health Education',
    'Educational Foundations and Curriculum',
    'Vocational and Technical Education',
    'Human Kinetics and Health Education',
    'Library and Information Science',
    'Educational Management',
    'Human Resource Development',
  ],
  Engineering: [
    'Civil Engineering',
    'Mechanical Engineering',
    'Electrical and Electronics Engineering',
    'Chemical Engineering',
    'Computer Engineering',
    'Agricultural and Bio-Resources Engineering',
    'Metallurgical and Materials Engineering',
    'Water Resources and Environmental Engineering',
    'Polymer and Textile Engineering',
    'Mining Engineering',
    'Agricultural Engineering',
    'Food Engineering',
    'Environmental Engineering',
  ],
  'Environmental Sciences': [
    'Architecture',
    'Building',
    'Estate Management',
    'Fine and Applied Arts',
    'Geography and Planning',
    'Quantity Surveying',
    'Urban and Regional Planning',
    'Environmental Education',
    'Environmental Sustainability',
    'Urban Planning',
    'Landscape Architecture',
    'Environmental Management',
  ],
  Law: [
    'Commercial Law',
    'Public Law',
    'Private Law',
    'International Law and Jurisprudence',
    'Criminal Law',
    'Constitutional Law',
    'Environmental Law',
    'Human Rights Law',
    'Property Law',
  ],
  'Management Sciences': [
    'Accounting',
    'Actuarial Science',
    'Banking and Finance',
    'Business Administration',
    'Business Management',
    'Insurance',
    'Marketing',
    'Transport Management',
    'Public Administration',
    'Human Resource Management',
    'Entrepreneurship',
    'Procurement Management',
  ],
  'Medical Sciences': [
    'Medicine',
    'Surgery',
    'Paediatrics',
    'Obstetrics and Gynaecology',
    'Ophthalmology',
    'Psychiatry',
    'Radiology',
    'Anaesthesia',
    'Community Medicine',
    'Oto-Rhino-Laryngology',
  ],
  'Pharmaceutical Sciences': [
    'Pharmaceutics',
    'Pharmaceutical Chemistry',
    'Pharmacology',
    'Pharmaceutical Microbiology',
    'Pharmaceutical Technology',
    'Industrial Pharmacy',
    'Pharmacognosy',
    'Clinical Pharmacy',
    'Pharmacy Practice',
  ],
  Science: [
    'Chemistry',
    'Physics',
    'Mathematics',
    'Computer Science',
    'Geology',
    'Microbiology',
    'Botany',
    'Zoology',
    'Statistics',
    'Biochemistry',
    'Environmental Science',
    'Science Laboratory Technology',
    'Plant Science',
    'Biotechnology',
    'Industrial Physics',
  ],
  'Social Sciences': [
    'Economics',
    'Political Science',
    'Sociology',
    'Psychology',
    'Geography',
    'Public Administration',
    'Anthropology',
    'International Relations',
    'Peace and Conflict Studies',
    'Social Work',
    'Mass Communication',
    'Development Studies',
    'Criminology',
    'Urban and Regional Planning',
  ],
  'Veterinary Medicine': [
    'Veterinary Anatomy',
    'Veterinary Physiology',
    'Veterinary Pathology',
    'Veterinary Microbiology',
    'Veterinary Parasitology',
    'Veterinary Pharmacology',
    'Veterinary Public Health',
    'Veterinary Surgery',
    'Veterinary Medicine',
    'Veterinary Radiology',
    'Veterinary Dentistry',
    'Veterinary Epidemiology',
  ],
  'Vocational Technical Education': [
    'Business Education',
    'Technical Education',
    'Agricultural Education',
    'Industrial Technical Education',
    'Home Economics Education',
    'Health Education',
    'Educational Technology',
    'Vocational and Technical Education',
    'Engineering Education',
    'Library and Information Science',
  ],
  'Communication and Media Studies': [
    'Mass Communication',
    'Journalism',
    'Public Relations',
    'Advertising',
    'Broadcasting',
    'Film and Television Production',
    'Digital Media',
    'Media Studies',
    'Communication Arts',
    'Media Technology',
  ],
  'Computing and Informatics': [
    'Computer Science',
    'Information Technology',
    'Software Engineering',
    'Cyber Security',
    'Data Science',
    'Artificial Intelligence',
    'Information Systems',
    'Computer Engineering',
    'Network Engineering',
    'Database Management',
  ],
  'Health Sciences': [
    'Nursing Science',
    'Medical Laboratory Science',
    'Radiography',
    'Physiotherapy',
    'Public Health',
    'Nutrition and Dietetics',
    'Health Information Management',
    'Environmental Health Science',
    'Occupational Therapy',
    'Speech and Language Therapy',
  ],
  Humanities: [
    'Philosophy',
    'History',
    'Linguistics',
    'Languages',
    'Religious Studies',
    'Theology',
    'Cultural Studies',
    'African Studies',
    'English Language and Literature',
    'French',
    'Spanish',
    'German',
    'Arabic',
    'Chinese',
  ],
  'Library and Information Science': [
    'Library and Information Science',
    'Archival Studies',
    'Information Management',
    'Records Management',
    'Information Technology',
    'Digital Libraries',
    'Information Systems',
    'Knowledge Management',
    'Information Retrieval',
    'Information Policy',
  ],
  Transport: [
    'Transport Management',
    'Logistics and Supply Chain Management',
    'Maritime Studies',
    'Aviation Management',
    'Urban and Regional Planning',
    'Transport Economics',
    'Transport Engineering',
    'Public Transport Planning',
    'Traffic Management',
  ],
};
